version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@samchon/openapi"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
    groups:
      Ecosystem:
        - patterns:
          - "@samchon/openapi"
          - "ts-node"
          - "typescript"
  - package-ecosystem: "npm"
    directory: "/test"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    open-pull-requests-limit: 25
    allow:
      - dependency-name: "@samchon/openapi"
      - dependency-name: "ts-node"
      - dependency-name: "ts-patch"
      - dependency-name: "typescript"
    groups:
      Ecosystem:
        - patterns:
          - "ts-node"
          - "ts-patch"
          - "typescript"